services:
  server:
    build:
      context: ./server  # This points to the server directory
      dockerfile: Dockerfile  # Ensure the correct Dockerfile name
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env  # Reference the .env file inside the server directory
    volumes:
      - ./server:/app
    
  client:
    build:
      context: ./client  # This points to the client directory
      dockerfile: Dockerfile  # Ensure the correct Dockerfile name
    ports:
      - "3000:80"
    depends_on:
      - server
